spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practices?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: devmysql
    password: Devmysql1234!
    data: classpath:init.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  #    show-sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: "head1ton@gmail.com"
#    password: "!@#$Oracle001"
#    protocol: smtp
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

#jwt:
#  expiration:
#    time: 90000

user:
  email: "head1ton@gmail.com"
  nickname: "head1ton"
  age: 70
  auth: false
  amount: 1010

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE